import json
import pytest
from pathlib import Path
from PIL import Image
from tools.promote import find_approved_items, promote_item, flatten_metadata


@pytest.fixture
def approved_item(tmp_project):
    """Create an approved staged item with media file."""
    item_dir = tmp_project / "staged" / "img-002"
    item_dir.mkdir(parents=True)
    img = Image.new("RGB", (1200, 800), color=(100, 100, 100))
    img.save(str(item_dir / "img-002.jpg"), "JPEG")
    img.save(str(item_dir / "original.jpg"), "JPEG")
    meta = {
        "id": "img-002",
        "media_type": "image",
        "original_filename": "photo.jpg",
        "file_size_kb": 200,
        "dimensions": "1200x800",
        "is_ai": True,
        "category": "landscape",
        "source": "Stable Diffusion XL",
        "attribution": "Generated by curator",
        "license": "CC0-1.0",
        "explanation": "The mountains show unnaturally smooth gradients.",
        "generation_method": "stable-diffusion",
        "prior_difficulty": 0.7,
        "tags": ["mountain", "sunset"],
        "exif": {"camera": None, "software": "Stable Diffusion", "date": None},
        "auto_ingest_date": "2026-03-29T10:00:00+00:00",
        "review_status": "approved",
    }
    (item_dir / "metadata.json").write_text(json.dumps(meta, indent=2))
    return item_dir


class TestFindApprovedItems:
    def test_finds_approved(self, tmp_project, approved_item):
        items = find_approved_items(tmp_project / "staged")
        assert len(items) == 1

    def test_skips_pending(self, tmp_project, approved_item):
        meta_path = approved_item / "metadata.json"
        meta = json.loads(meta_path.read_text())
        meta["review_status"] = "pending"
        meta_path.write_text(json.dumps(meta))
        items = find_approved_items(tmp_project / "staged")
        assert len(items) == 0


class TestFlattenMetadata:
    def test_strips_internal_fields(self, approved_item):
        meta = json.loads((approved_item / "metadata.json").read_text())
        flat = flatten_metadata(meta)
        assert "exif" not in flat
        assert "review_status" not in flat
        assert "auto_ingest_date" not in flat
        assert "original_filename" not in flat
        assert "file_size_kb" not in flat
        assert "dimensions" not in flat

    def test_keeps_production_fields(self, approved_item):
        meta = json.loads((approved_item / "metadata.json").read_text())
        flat = flatten_metadata(meta)
        assert flat["id"] == "img-002"
        assert flat["is_ai"] is True
        assert flat["category"] == "landscape"
        assert flat["tags"] == ["mountain", "sunset"]

    def test_unwraps_source_tagged_values(self):
        meta = {
            "id": "img-003",
            "media_type": "image",
            "is_ai": {"value": True, "confidence": "high", "source": "claude-vision"},
            "category": {"value": "animal", "source": "claude-vision"},
            "tags": {"value": ["cat"], "source": "claude-vision"},
            "source": "Test",
            "attribution": "Test",
            "license": "CC0-1.0",
            "explanation": {"value": "A cat.", "source": "claude-vision"},
            "generation_method": "photograph",
            "prior_difficulty": 0.5,
            "review_status": "approved",
            "exif": {},
            "auto_ingest_date": "2026-01-01",
            "original_filename": "cat.jpg",
            "file_size_kb": 100,
            "dimensions": "800x600",
        }
        flat = flatten_metadata(meta)
        assert flat["is_ai"] is True
        assert flat["category"] == "animal"
        assert flat["tags"] == ["cat"]
        assert flat["explanation"] == "A cat."


class TestPromoteItem:
    def test_copies_to_assets_and_updates_content(self, tmp_project, approved_item):
        content = json.loads((tmp_project / "content.json").read_text())
        assert len(content["items"]) == 1

        promote_item(
            approved_item,
            assets_dir=tmp_project / "assets",
            content_json=tmp_project / "content.json",
        )

        assert (tmp_project / "assets" / "img-002.jpg").exists()

        content = json.loads((tmp_project / "content.json").read_text())
        assert len(content["items"]) == 2
        new_item = content["items"][1]
        assert new_item["id"] == "img-002"
        assert new_item["url"] == "assets/img-002.jpg"
        assert "exif" not in new_item
        assert "review_status" not in new_item

        assert not approved_item.exists()
