#!/usr/bin/env python3
"""Quick ingest: stage + review + promote in one pass with minimal prompting.

Usage:
    python3 tools/quick_ingest.py [--all] [--count N] [--ai] [--real]
                                   [--explanation "text"] [--config path]
"""

import argparse
import platform
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools.auto_ingest import find_ingestable_files, load_config
from tools.lib.content import load_content, next_item_id, save_content
from tools.lib.extract import detect_media_type, probe_video
from tools.lib.files import optimize_image

# Default explanations when curator skips the prompt
PLACEHOLDER_EXPLANATIONS = {
    ("image", True):  (
        "This image was generated by AI. Look for telltale signs like unusual "
        "textures, inconsistent lighting, or artifacts in fine details."
    ),
    ("image", False): (
        "This is a real photograph. Notice the natural imperfections, consistent "
        "lighting, and authentic detail that AI often struggles to replicate."
    ),
    ("video", True):  (
        "This video was generated by AI. Watch for unnatural motion, flickering "
        "details, or inconsistent physics."
    ),
    ("video", False): (
        "This is real video footage. The natural motion, consistent physics, and "
        "authentic imperfections distinguish it from AI-generated content."
    ),
}


def open_file(path: Path) -> None:
    """Open a file in the platform default viewer (non-blocking)."""
    if platform.system() == "Darwin":
        subprocess.Popen(["open", str(path)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    elif platform.system() == "Linux":
        subprocess.Popen(["xdg-open", str(path)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def prompt_is_ai() -> bool:
    """Prompt until the curator enters 'a' or 'r'. Returns True for AI."""
    while True:
        answer = input("  AI or Real? [a/r]: ").strip().lower()
        if answer == "a":
            return True
        if answer == "r":
            return False
        print("  Enter 'a' for AI or 'r' for Real.")


def process_and_promote(
    src: Path,
    content_json: Path,
    assets_dir: Path,
    processed_dir: Path,
    is_ai: bool,
    explanation: str,
    config: dict,
) -> dict:
    """Optimize/validate src, write directly to assets/, append to content.json.

    Moves the original to processed_dir so nothing is silently deleted.
    Returns the content.json item dict.
    """
    media_type = detect_media_type(src)

    # Reload content each call so sequential IDs are collision-free across items
    content = load_content(content_json)
    item_id = next_item_id(content, media_type, staged_dir=None)

    assets_dir.mkdir(parents=True, exist_ok=True)
    processed_dir.mkdir(parents=True, exist_ok=True)

    out_ext = ".jpg" if media_type == "image" else src.suffix.lower()
    asset_dest = assets_dir / f"{item_id}{out_ext}"

    if media_type == "image":
        optimize_image(
            src, asset_dest,
            max_width=config["max_image_width"],
            quality=config["image_quality"],
        )
    else:
        video_info = probe_video(src)
        max_dur = config["max_video_duration_sec"]
        max_mb = config["max_video_file_mb"]
        if video_info["duration_sec"] > max_dur:
            raise ValueError(
                f"Video too long: {video_info['duration_sec']:.1f}s "
                f"(max {max_dur}s). Trim before ingesting."
            )
        if video_info["file_size_mb"] > max_mb:
            raise ValueError(
                f"Video too large: {video_info['file_size_mb']:.1f}MB "
                f"(max {max_mb}MB). Compress before ingesting."
            )
        shutil.copy2(src, asset_dest)

    item = {
        "id": item_id,
        "media_type": media_type,
        "url": f"assets/{asset_dest.name}",
        "is_ai": is_ai,
        "source": None,
        "attribution": None,
        "license": None,
        "explanation": explanation,
        "category": None,
        "generation_method": "ai-generated" if is_ai else "photograph",
        "prior_difficulty": 0.5,
        "tags": None,
    }

    content["items"].append(item)
    save_content(content_json, content)

    shutil.move(str(src), str(processed_dir / src.name))

    return item


def main():
    parser = argparse.ArgumentParser(
        description="Quick ingest: process ingest/ files directly to assets/ + content.json"
    )
    parser.add_argument("--all", action="store_true", help="Process all files in ingest/ (default: 1)")
    parser.add_argument("--count", type=int, default=1, help="Number of files to process (default: 1)")
    parser.add_argument("--ai", action="store_true", help="Mark all items as AI — skips is_ai prompt")
    parser.add_argument("--real", action="store_true", help="Mark all items as real — skips is_ai prompt")
    parser.add_argument("--explanation", type=str, default=None, help="Apply same explanation to all items")
    parser.add_argument("--config", type=Path, default=None, help="Path to ingest_config.yaml")
    args = parser.parse_args()

    if args.ai and args.real:
        print("Error: --ai and --real are mutually exclusive.")
        sys.exit(1)

    project_root = Path(__file__).resolve().parent.parent
    config_path = args.config or (project_root / "tools" / "ingest_config.yaml")
    config = load_config(config_path)

    ingest_dir  = project_root / config["ingest_dir"]
    assets_dir  = project_root / config["assets_dir"]
    content_json = project_root / config["content_json"]
    processed_dir = ingest_dir / "processed"

    if not ingest_dir.exists():
        ingest_dir.mkdir(parents=True)
        print(f"Created {ingest_dir}/. Drop files there and re-run.")
        return

    files = find_ingestable_files(ingest_dir)
    if not files:
        print(f"No supported files in {ingest_dir}/. Drop images or videos there first.")
        return

    count = len(files) if args.all else min(args.count, len(files))
    to_process = files[:count]

    print(f"Found {len(files)} file(s) in ingest/. Processing {count}.\n")

    added = ai_added = real_added = 0

    for src in to_process:
        print(f"  {src.name}")
        open_file(src)

        if args.ai:
            is_ai = True
        elif args.real:
            is_ai = False
        else:
            is_ai = prompt_is_ai()

        if args.explanation:
            explanation = args.explanation
        else:
            raw = input("  Explanation (Enter to skip): ").strip()
            if raw:
                explanation = raw
            else:
                media_type = detect_media_type(src)
                explanation = PLACEHOLDER_EXPLANATIONS[(media_type, is_ai)]

        try:
            item = process_and_promote(
                src=src,
                content_json=content_json,
                assets_dir=assets_dir,
                processed_dir=processed_dir,
                is_ai=is_ai,
                explanation=explanation,
                config=config,
            )
            label = "AI" if is_ai else "Real"
            print(f"  ✓ {src.name} → {item['id']} ({label}) → {item['url']}\n")
            added += 1
            if is_ai:
                ai_added += 1
            else:
                real_added += 1
        except Exception as exc:
            print(f"  ✗ {src.name} — ERROR: {exc}\n")

    # Summary
    content = load_content(content_json)
    total = len(content["items"])
    total_ai = sum(1 for i in content["items"] if i.get("is_ai"))
    total_real = total - total_ai
    pct_ai = round(100 * total_ai / total) if total else 0

    total_bytes = sum(f.stat().st_size for f in assets_dir.iterdir() if f.is_file())
    total_mb = total_bytes / (1024 * 1024)

    print(f"Done: {added} item(s) added ({ai_added} AI, {real_added} real)")
    print(f"content.json: {total} items total ({total_ai} AI / {total_real} real = {pct_ai}% AI)")
    print(f"Assets: {total_mb:.1f} MB")
    if added > 0:
        print(f"\nNext: git add assets/ content.json && git commit")


if __name__ == "__main__":
    main()
